### ISSUE TITLE
few questions about what arc game is about

### ISSUE THREAD

**Issue by evanthebouncy** [volotat/ARC-Game#3]
trying to understand what this is in the context of the original ARC dataset. specifically:

For ARC game, what was the basis of their categorization into different levels of difficulty?  And - are you collecting data from people?

**Comment by volotat** [comment]
It was sorted by my own subjective opinion. I tried to make some mathematical sense of the difficulty of the task at first, but this question is surprisingly difficult. Some of the ideas I explored was related to entropy of the image and shortest programs that can transform input grid into output ones, but none of these even in theory can approximate "difficulty". For example it is crucial to have structure of the data given (how cells in the grid related to each other), because depending on that structure the shortest program will be different.

**Comment by evanthebouncy** [comment]
are you collecting data from people? Or do you intend to do so anytime soon? Or will this just be a stand-alone website where people interact with it but you do not track their interactions?

**Comment by volotat** [comment]
No, there are no tracking at all. The website does not collect anything. It even stores progress locally within browser.

**Comment by evanthebouncy** [comment]
I see. did you make this for fun after seeing squid games? haha
